### ISSUE TITLE
reduce clone and own

### ISSUE THREAD

**Issue by rabbah** [ibm-functions/runtime-python#3]
if the action proxy and runner files here are the same as the ones in the apache runtime repo, i suggest the docker file fetches them directly rather than cloning and owning these files.

**Comment by csantanapr** [comment]
Yeah I agree it would be good to figure out how to http get a single file from a a specific guy hash/tag and not bring down the whole repo with a fit clone

**Comment by csantanapr** [comment]
Already addressed
