### ISSUE TITLE
Add etcd3 package to python:3.7

### ISSUE THREAD

**Issue by csantanapr** [ibm-functions/runtime-python#73]
We got feedback from customers that they would like to see the package `etcd3` included in python:3.7 runtime
https://pypi.org/project/etcd3/

**Comment by csantanapr** [comment]
The package is added here https://github.com/ibm-functions/runtime-python/blob/master/python3.7/requirements.txt#L42

But the image is not in production yet, I will close next week when the image is in production.

**Comment by csantanapr** [comment]
@bruceadams this is in production in all regions for IBM Cloud Functions use the runtime `python:3.7` 🚀

**Comment by bruceadams** [comment]
Can you tell me what image tag (on https://hub.docker.com/r/ibmfunctions/action-python-v3.7/tags ) is the one that is running live? Or, can you update the `latest` tag to point to the image running in production?

**Comment by bruceadams** [comment]
Background: my packaging process runs a `pip3 install` within the image that I expect to run on in IBM Cloud Functions. I've been using `ibmfunctions/action-python-v3.7:latest` but `latest` does not have `etcd3` installed, so my build goes ahead and adds `etcd3` into my zip package.
